// Shared sound definitions used by both the Chrome extension (content.js)
// and the web page (page.js).
// - Extension: loaded via manifest.json content_scripts before content.js
// - Web page:  loaded via <script> in index.html before page.js
const SOUNDS = [
  { label: "🦆 アヒル",         file: "voice/animal/01_duck.mp3" },
  { label: "🐑 ヒツジ",         file: "voice/animal/02_sheep.mp3" },
  { label: "🐐 ヤギ",           file: "voice/animal/03_goat.mp3" },
  { label: "🦊 キツネ",         file: "voice/animal/04_fox.mp3" },
  { label: "🐧 ペンギン",       file: "voice/animal/05_penguin.mp3" },
  { label: "🦭 セイウチ",       file: "voice/animal/06_walrus.mp3" },
  { label: "🐻‍❄️ ホッキョクグマ", file: "voice/animal/07_polar_bear.mp3" },
  { label: "🦌 トナカイ",       file: "voice/animal/08_reindeer.mp3" },
  { label: "🦜 オウム",         file: "voice/animal/09_parrot.mp3" },
  { label: "🦩 フラミンゴ",     file: "voice/animal/10_flamingo.mp3" },
  { label: "🦉 フクロウ",       file: "voice/animal/11_owl.mp3" },
  { label: "🦅 ワシ",           file: "voice/animal/12_eagle.mp3" },
  { label: "🦁 ライオン",       file: "voice/animal/13_lion.mp3" },
  { label: "🦏 サイ",           file: "voice/animal/14_rhinoceros.mp3" },
  { label: "🐘 ゾウ",           file: "voice/animal/15_elephant.mp3" },
  { label: "🦛 カバ",           file: "voice/animal/16_hippopotamus.mp3" },
  { label: "🐻 クマ",           file: "voice/animal/17_bear.mp3" },
  { label: "🐯 トラ",           file: "voice/animal/18_tiger.mp3" },
  { label: "🦍 ゴリラ",         file: "voice/animal/19_gorilla.mp3" },
  { label: "🐼 パンダ",         file: "voice/animal/20_panda.mp3" },
  { label: "🦥 ナマケモノ",     file: "voice/animal/21_sloth.mp3" },
  { label: "🐸 カエル",         file: "voice/animal/22_frog.mp3" },
  { label: "🐶 イヌ",           file: "voice/animal/23_dog.mp3" },
  { label: "🐱 ネコ",           file: "voice/animal/24_cat.mp3" },
  { label: "🐰 ウサギ",         file: "voice/animal/25_rabbit.mp3" },
  { label: "🐢 カメ",           file: "voice/animal/26_turtle.mp3" },
  { label: "🐴 ウマ",           file: "voice/animal/27_horse.mp3" },
  { label: "🐮 ウシ",           file: "voice/animal/28_cow.mp3" },
  { label: "🐹 ハムスター",     file: "voice/animal/29_hamster.mp3" },
  { label: "🐌 カタツムリ",     file: "voice/animal/30_snail.mp3" },
];
